import { SiteData } from "@/types";

export const DEFAULT_SITE_DATA: SiteData = {
  projects: [
    {
      id: "ma",
      name: "Malindi Ocean View Acres",
      location: "Malindi, Kilifi County",
      price: "KES 1.5M",
      priceSubtitle: "per 1-acre plot",
      plotSize: "1 Acre",
      statusBadge: "Selling Fast",
      shortDesc:
        "Spacious 1-acre plots set in the heart of Kenya's premier coastal town. Ideal for holiday homes, eco-lodges, farming, or long-term investment. Just minutes from Malindi Beach and the airport.",
      type: "land",
      imageUrl:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
      features: [
        "1 Acre per Plot",
        "Title Deed Ready",
        "Near the Coast",
        "Road Access",
        "Water Available",
      ],
      gallery: [
        { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1540541338537-b09ec4b6e3f5?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1473496169904-658ba7574b0d?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=700&q=80" },
      ],
      availBadge: "🔥 Selling Fast",
      availNote: "Limited plots remaining",
      fullDesc:
        "Own a piece of Kenya's most beautiful coastline. Malindi Ocean View Acres offers spacious 1-acre plots in Kenya's premier coastal town, just minutes from Malindi Beach and the airport. These plots are ideal for building a holiday home, setting up an Airbnb retreat, small-scale farming, or holding as a long-term land investment. Every plot comes with a clean, registered title deed — verified and ready for transfer.",
      specs: [
        { value: "1 Acre", label: "Plot Size" },
        { value: "KES 1.5M", label: "Price / Plot" },
        { value: "Ready", label: "Title Deed" },
        { value: "Borehole", label: "Water Supply" },
        { value: "2 km", label: "From Beach" },
        { value: "48", label: "Total Plots" },
      ],
      detailFeatures: [
        "Clean, registered title deed",
        "Tarmac road access to plot",
        "Borehole & water available",
        "Electricity on the road",
        "Surveyed & beaconed plots",
        "Free guided site visits",
        "2 km from Malindi Beach",
        "4 km from Malindi Airport",
        "Rated land — low rates",
        "Flexible payment plans",
      ],
      paymentPlans: [
        { label: "Option A", deposit: "100%", detail: "Full cash payment\nImmediate title transfer" },
        { label: "Option B", deposit: "30%", detail: "Deposit, then balance\nover 6 months", featured: true },
        { label: "Option C", deposit: "20%", detail: "Deposit, then balance\nover 12 months" },
      ],
    },
    {
      id: "ko",
      name: "Konza Technopolis Plots",
      location: "Konza, Machakos County",
      price: "KES 450K",
      priceSubtitle: "per 1/8-acre plot",
      plotSize: "1/8 Acre",
      statusBadge: "Tech City Zone",
      shortDesc:
        "Strategically positioned 1/8-acre residential plots adjacent to Kenya's Silicon Savannah — Konza Technopolis. The fastest appreciating land corridor in Kenya right now.",
      type: "land",
      imageUrl:
        "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80",
      features: [
        "1/8 Acre per Plot",
        "Title Deed Ready",
        "Near Konza City",
        "Power and Water",
        "Tarmac Access",
      ],
      gallery: [
        { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1503751071777-d2918b21bbd9?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&q=80" },
      ],
      availBadge: "⚡ High Demand",
      availNote: "Limited 1/8-acre plots",
      fullDesc:
        "Strategically positioned plots adjacent to Konza Technopolis — Kenya's Silicon Savannah. Approved by the government as Kenya's first smart city, Konza is set to host ICT firms, universities, hospitals, and government agencies. Invest now before prices surge further.",
      specs: [
        { value: "1/8 Acre", label: "Plot Size" },
        { value: "KES 450K", label: "Price / Plot" },
        { value: "Ready", label: "Title Deed" },
        { value: "Mains", label: "Water Supply" },
        { value: "SGR Nearby", label: "Transport" },
        { value: "60", label: "Total Plots" },
      ],
      detailFeatures: [
        "Title deed ready",
        "Near SGR Konza Station",
        "Power & water available",
        "Tarmac road access",
        "Surveyed & beaconed",
        "Free site visits",
        "Next to Konza Smart City",
        "High appreciation area",
        "Flexible payment plans",
        "Easy transfer process",
      ],
      paymentPlans: [
        { label: "Option A", deposit: "100%", detail: "Full cash payment\nImmediate title transfer" },
        { label: "Option B", deposit: "30%", detail: "Deposit, then balance\nover 6 months", featured: true },
        { label: "Option C", deposit: "20%", detail: "Deposit, then balance\nover 12 months" },
      ],
    },
    {
      id: "ka",
      name: "Kamakis Urban Residences",
      location: "Kamakis, Ruiru",
      price: "From 3.2M",
      priceSubtitle: "per apartment",
      plotSize: "1BR–3BR",
      statusBadge: "Coming Soon",
      shortDesc:
        "Modern apartments strategically located at the Kamakis roundabout, Ruiru — one of Nairobi's fastest growing suburbs. Pre-register your interest today.",
      type: "apt",
      imageUrl:
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&q=80",
      features: [
        "Modern Apartments",
        "Kamakis, Ruiru",
        "1BR, 2BR & 3BR",
        "Ample Parking",
        "24/7 Security",
      ],
      gallery: [
        { url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&q=80" },
        { url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=700&q=80" },
        { url: "" },
        { url: "" },
      ],
      availBadge: "🏗️ Coming Soon",
      availNote: "Pre-registration open",
      fullDesc:
        "Kamakis Urban Residences brings contemporary living to one of Nairobi's fastest growing corridors. Located at the Kamakis roundabout junction, these apartments offer the perfect blend of urban convenience and suburban comfort.",
      specs: [
        { value: "1BR–3BR", label: "Unit Types" },
        { value: "From 3.2M", label: "Starting Price" },
        { value: "Q4 2026", label: "Completion" },
        { value: "Mains", label: "Water Supply" },
        { value: "Kamakis", label: "Location" },
        { value: "48", label: "Total Units" },
      ],
      detailFeatures: [
        "Modern interior finishes",
        "Ample parking space",
        "24/7 security",
        "Backup generator",
        "Rooftop terrace",
        "Gym & recreation",
        "Near Eastern Bypass",
        "Easy city access",
        "Flexible payment plans",
        "Pre-registration discount",
      ],
      paymentPlans: [
        { label: "Option A", deposit: "100%", detail: "Full cash payment\nBest pricing" },
        { label: "Option B", deposit: "30%", detail: "Deposit, then balance\nover 12 months", featured: true },
        { label: "Option C", deposit: "20%", detail: "Deposit, then balance\nover 24 months" },
      ],
    },
  ],
  banners: [
    {
      img: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&q=80",
      tag: "Legal",
      title: "Title Deed Verified",
      desc: "Every plot comes with a clean, verified title deed.",
    },
    {
      img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=700&q=80",
      tag: "Finance",
      title: "Flexible Payment Plans",
      desc: "Secure your plot with a deposit and pay over time.",
    },
    {
      img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
      tag: "Service",
      title: "Free Site Visits",
      desc: "We take you to any site at no cost.",
    },
    {
      img: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=700&q=80",
      tag: "Investment",
      title: "High Appreciation Areas",
      desc: "Among Kenya's fastest-appreciating corridors.",
    },
  ],
  testimonials: [
    {
      initials: "JK",
      name: "James Kamau",
      role: "Malindi Plot Owner — Nairobi",
      quote:
        "I bought a 1-acre plot in Malindi through ArdhiSoko and the process was so smooth. Title deed was ready within 3 weeks. The team organised a free site visit and I fell in love with the land immediately.",
    },
    {
      initials: "AW",
      name: "Amina Wanjiru",
      role: "Konza Plot Owner — Mombasa",
      quote:
        "The Konza plots are the best investment I have made. ArdhiSoko was transparent from day one — no hidden charges. The payment plan made it very affordable. Highly recommend to anyone looking for land near the SGR.",
    },
    {
      initials: "DO",
      name: "David Ochieng",
      role: "Kamakis Apartments — Kisumu",
      quote:
        "Professional, honest, and fast. I was sceptical at first but ArdhiSoko proved me wrong. I registered my interest for Kamakis apartments and have been updated every step of the way. Excellent customer service.",
    },
  ],
  blogPosts: [
    {
      img: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80",
      category: "market",
      statusBadge: "Trending",
      location: "Konza, Machakos County",
      title: "Why Konza Technopolis Land is Doubling in Value Every 2 Years",
      excerpt:
        "With the SGR station, data centres, and government offices all confirmed for Konza, early investors are already seeing massive returns on their land.",
      date: "March 2025",
      readTime: "4 min read",
    },
    {
      img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
      category: "update",
      statusBadge: "Hot",
      location: "Malindi, Kilifi County",
      title: "Malindi Phase 2 Now Open — Only 12 Plots Remaining",
      excerpt:
        "Following the sell-out success of Phase 1, ArdhiSoko has released Phase 2 of the Malindi Ocean View Acres project. Act fast — demand is extremely high.",
      date: "February 2025",
      readTime: "3 min read",
    },
    {
      img: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&q=80",
      category: "tips",
      statusBadge: "Must Read",
      location: "Kenya Wide",
      title: "5 Things to Check Before Buying Land in Kenya",
      excerpt:
        "From title deed verification to land rates clearance — here is a simple checklist every Kenyan land buyer must go through before signing anything.",
      date: "January 2025",
      readTime: "5 min read",
    },
    {
      img: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=700&q=80",
      category: "market",
      statusBadge: "New",
      location: "Malindi, Kilifi County",
      title: "Malindi Tourism Boom is Pushing Property Prices Up",
      excerpt:
        "International tourism arrivals at Malindi Airport hit a 10-year high. Property investors who moved early are now sitting on significant unrealised gains.",
      date: "December 2024",
      readTime: "4 min read",
    },
    {
      img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=700&q=80",
      category: "tips",
      statusBadge: "Guide",
      location: "Kenya Wide",
      title: "How to Use a Payment Plan to Buy Land Without a Bank Loan",
      excerpt:
        "Many Kenyans don't know you can own land without going to the bank. Here's how ArdhiSoko's flexible plans work — and how to qualify.",
      date: "November 2024",
      readTime: "6 min read",
    },
    {
      img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
      category: "update",
      statusBadge: "Update",
      location: "Kamakis, Ruiru",
      title: "Kamakis Apartments: Pre-Registration Now Open",
      excerpt:
        "Demand has been overwhelming. We've opened pre-registration for our Kamakis Urban Residences project. Early birds get priority unit selection and special pricing.",
      date: "October 2024",
      readTime: "3 min read",
    },
  ],
  contact: {
    phone: "+254 712 345 678",
    email: "info@ardhisoko.co.ke",
    whatsapp: "+254712345678",
    address: "Nairobi, Kenya",
    facebook: "https://facebook.com/ardhisoko",
    instagram: "https://instagram.com/ardhisoko",
    youtube: "",
  },
  logo: {
    part1: "Ardhi",
    part2: "Soko",
    tagline: "Kenya's Trusted Land Marketplace",
    heroImage:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=80",
    heroOverlayText: "Own Prime Land. Invest Smart.",
  },
};
